POST http://localhost:8080/rest/bankslip
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "due_date": "2018-10-25",
  "total_in_cents" : "100" ,
  "customer" : "Trillian Company"
}

###

GET http://localhost:8080/rest/bankslip/5ad9dc07-2dcc-44c7-ae51-64e03b67b7be

###

DELETE http://localhost:8080/rest/bankslip/5ad9dc07-2dcc-44c7-ae51-64e03b67b7be

###